<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Basma" failures="1" tests="3" name="Default test" time="8.682" errors="0" timestamp="2024-12-09T07:21:35 GMT">
  <testcase classname="TestCases.LoginTests" name="TC01_ValidScenarioLoginVerification" time="0.787"/>
  <testcase classname="TestCases.LoginTests" name="TC02_InValidScenariosLoginVerification" time="0.293"/>
  <testcase classname="TestCases.ManagerTests" name="TC03_ManagerUserIdPresesnce" time="0.0">
    <failure type="org.testng.TestNGException" message="
Method public static void TestCases.ManagerTests.TC03_ManagerUserIdPresesnce(java.lang.String,java.lang.String) requires a @DataProvider named : LoginData in class Utilities.DataDrivenProvider">
      <![CDATA[org.testng.TestNGException: 
Method public static void TestCases.ManagerTests.TC03_ManagerUserIdPresesnce(java.lang.String,java.lang.String) requires a @DataProvider named : LoginData in class Utilities.DataDrivenProvider
at org.testng.internal.Parameters.findDataProvider(Parameters.java:532)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC03_ManagerUserIdPresesnce -->
</testsuite> <!-- Default test -->
