<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Basma" failures="2" tests="4" name="Test" time="6.826" errors="0" timestamp="2024-12-13T10:37:39 GMT">
  <testcase classname="TestCases.LoginTests" name="TC01_ValidScenarioLoginVerification" time="0.727"/>
  <testcase classname="TestCases.LoginTests" name="TC02_InValidScenariosLoginVerification" time="0.363">
    <failure type="java.lang.AssertionError" message="expected [User or Password is no valid] but found [User or Password is not valid]">
      <![CDATA[java.lang.AssertionError: expected [User or Password is no valid] but found [User or Password is not valid]
at Pages.LoginPage.InvalidLoginValidation(LoginPage.java:106)
at TestCases.LoginTests.TC02_InValidScenariosLoginVerification(LoginTests.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC02_InValidScenariosLoginVerification -->
  <testcase classname="TestCases.ManagerTests" name="TC03_LoginWithManagerID" time="0.904">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Pages.ManagerHomePage.ValidateUserInCorrectURL(ManagerHomePage.java:45)
at TestCases.ManagerTests.TC03_LoginWithManagerID(ManagerTests.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC03_LoginWithManagerID -->
  <testcase classname="TestCases.ManagerTests" name="TC04_ManagerUserIdPresesnce" time="0.0">
    <skipped/>
  </testcase> <!-- TC04_ManagerUserIdPresesnce -->
</testsuite> <!-- Test -->
